# Generated by Django 5.0.6 on 2025-08-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المرشح')),
                ('role', models.CharField(default='مرشح مجلس النواب', max_length=200, verbose_name='المنصب')),
                ('governorate_id', models.PositiveIntegerField(help_text='معرف المحافظة من ملف JSON', verbose_name='المحافظة')),
                ('constituency', models.CharField(max_length=200, verbose_name='الدائرة الانتخابية')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_profiles/', verbose_name='الصورة الشخصية')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='candidate_banners/', verbose_name='صورة البانر')),
                ('bio', models.TextField(blank=True, verbose_name='البيان الشخصي')),
                ('electoral_program', models.TextField(blank=True, help_text='البرنامج الانتخابي المفصل للمرشح', verbose_name='البرنامج الانتخابي')),
                ('message_to_voters', models.TextField(blank=True, help_text='كلمة موجزة من المرشح لمنتخبيه', verbose_name='كلمة للمنتخبين')),
                ('youtube_video_url', models.URLField(blank=True, help_text='رابط فيديو تعريفي أو برنامج انتخابي على يوتيوب', verbose_name='رابط فيديو يوتيوب')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('website_url', models.URLField(blank=True, verbose_name='الموقع الشخصي')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مرشح مميز في المحافظة')),
                ('election_symbol', models.CharField(blank=True, max_length=50, verbose_name='رمز الترشح')),
                ('election_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الانتخابي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرشح',
                'verbose_name_plural': 'المرشحون',
            },
        ),
        migrations.CreateModel(
            name='ElectoralPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الوعد')),
                ('description', models.TextField(verbose_name='وصف الوعد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_promises', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'وعد انتخابي',
                'verbose_name_plural': 'الوعود الانتخابية',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_candidate', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'مرشح مميز',
                'verbose_name_plural': 'المرشحون المميزون',
            },
        ),
        migrations.CreateModel(
            name='PublicServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(verbose_name='سنة البداية')),
                ('end_year', models.PositiveIntegerField(verbose_name='سنة النهاية')),
                ('position', models.CharField(max_length=300, verbose_name='المنصب')),
                ('description', models.TextField(verbose_name='وصف الإنجازات والمسؤوليات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'تاريخ في العمل العام',
                'verbose_name_plural': 'التاريخ في العمل العام',
                'ordering': ['-start_year'],
            },
        ),
    ]
