# Generated by Django 5.0.6 on 2025-08-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('area_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المنطقة')),
                ('area_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المنطقة')),
                ('address', models.TextField(blank=True, verbose_name='عنوان المراسلات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مواطن',
                'verbose_name_plural': 'المواطنون',
            },
        ),
    ]
