steps:
  # Build container image using the Dockerfile at project root
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: 'Build Image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest']
    id: 'Push Image'

# Define the image to be pushed (for build history)
images:
  - 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest'

# Build timeout
timeout: '1200s'

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY

