steps:
  # Step 1: Install dependencies, collect static, migrate, and test in a single step
  - name: 'python:3.11-slim-buster'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements/prod.txt &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate --noinput &&
        python manage.py test
    id: 'Run Django Commands'

  # Step 2: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest'
      - '.'
      - '-f'
      - 'docker/prod/Dockerfile'
    id: 'Build Image'

  # Step 3: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest']
    id: 'Push Image'

# Define the image to be pushed
images:
  - 'europe-west1-docker.pkg.dev/stalwart-star-468902-j1/naebak-repo/naebak-app:latest'

# Set a timeout for the build
timeout: '1200s'

# Add build options to solve the logging issue
options:
  logging: CLOUD_LOGGING_ONLY
