version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DB_HOST=db
      - DB_NAME=naebak_db
      - DB_USER=naebak_user
      - DB_PASSWORD=naebak_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ../media:/app/media
      - ../logs:/app/logs
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=naebak_db
      - POSTGRES_USER=naebak_user
      - POSTGRES_PASSWORD=naebak_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../static:/app/static
      - ../media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:

