# Generated by Django 5.0.6 on 2025-08-17 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المرسل')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد المرسل')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments/', verbose_name='مرفق')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidates.candidate')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.message')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المرسل المسجل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-timestamp'],
            },
        ),
    ]
