# Generated by Django 5.0.6 on 2025-08-17 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='حالة الخبر')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجل')], default='normal', max_length=20, verbose_name='أولوية الخبر')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='عرض في الصفحة الرئيسية')),
                ('show_on_ticker', models.BooleanField(default=True, verbose_name='عرض في الشريط الإخباري')),
                ('ticker_speed', models.PositiveIntegerField(default=50, verbose_name='سرعة التمرير (بالثانية)')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف ميتا')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='الكلمات المفتاحية')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-priority', '-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'publish_date'], name='news_news_status_ea155c_idx'), models.Index(fields=['priority', 'created_at'], name='news_news_priorit_eb5411_idx')],
            },
        ),
    ]
