# Generated by Django 5.0.6 on 2025-08-17 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('register', 'تسجيل حساب جديد'), ('profile_update', 'تحديث الملف الشخصي'), ('message_sent', 'إرسال رسالة'), ('message_reply', 'الرد على رسالة'), ('rating_given', 'إعطاء تقييم'), ('vote_cast', 'إدلاء بصوت'), ('promise_created', 'إنشاء وعد انتخابي'), ('promise_updated', 'تحديث وعد انتخابي'), ('promise_deleted', 'حذف وعد انتخابي'), ('news_created', 'إنشاء خبر'), ('news_updated', 'تحديث خبر'), ('news_deleted', 'حذف خبر'), ('news_published', 'نشر خبر'), ('candidate_created', 'إنشاء حساب مرشح'), ('candidate_updated', 'تحديث بيانات مرشح'), ('candidate_deleted', 'حذف حساب مرشح'), ('user_created', 'إنشاء حساب مستخدم'), ('user_updated', 'تحديث بيانات مستخدم'), ('user_deleted', 'حذف حساب مستخدم'), ('backup_created', 'إنشاء نسخة احتياطية'), ('backup_restored', 'استعادة نسخة احتياطية'), ('system_error', 'خطأ في النظام'), ('security_alert', 'تنبيه أمني')], max_length=50, verbose_name='نوع النشاط')),
                ('description', models.TextField(verbose_name='وصف النشاط')),
                ('severity', models.CharField(choices=[('info', 'معلومات'), ('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], default='info', max_length=20, verbose_name='مستوى الأهمية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='مفتاح الجلسة')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت النشاط')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات الأنشطة',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_activi_user_id_81b1f1_idx'), models.Index(fields=['action_type', 'timestamp'], name='core_activi_action__5424a6_idx'), models.Index(fields=['severity', 'timestamp'], name='core_activi_severit_3034da_idx'), models.Index(fields=['ip_address', 'timestamp'], name='core_activi_ip_addr_373528_idx')],
            },
        ),
    ]
