# Generated by Django 5.0.6 on 2025-08-17 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='التقييم بالنجوم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التقييم')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='candidates.candidate')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المواطن')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-timestamp'],
                'unique_together': {('candidate', 'citizen')},
            },
        ),
        migrations.CreateModel(
            name='RatingReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='رد المرشح')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الرد')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='voting.rating')),
            ],
            options={
                'verbose_name': 'رد على تقييم',
                'verbose_name_plural': 'الردود على التقييمات',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('approve', 'أؤيد'), ('disapprove', 'أعارض')], max_length=20, verbose_name='نوع التصويت')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التصويت')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المواطن')),
            ],
            options={
                'verbose_name': 'تصويت',
                'verbose_name_plural': 'التصويتات',
                'ordering': ['-timestamp'],
                'unique_together': {('candidate', 'citizen')},
            },
        ),
    ]
